# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cf0d854f14df44fbba9ed6f697ba2f59bce1758ad214f66f3d60bd828c3d36b00fbf16d3cbdaa82b299d8a3df6bbf8016edf8c10927e7a277c9914b6052f401

test:
  secret_key_base: 366a201971eb8876183397395eedccd5fa543a067b8039158e79beeeb5448793978271659c0d937bf725e33d39ea80581a350bc73b6e7d46d94f4e8259697235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
